CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_hh/mild_crossrecon_samplecovcond/z5/trial0/models/final_100.pth --cov >> logs/2023/downsampled/bp_hh/mild_crossrecon_samplecovcond/z5/trial0.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_hh/mild_crossrecon_samplecovcond/z5/trial1/models/final_100.pth --cov >> logs/2023/downsampled/bp_hh/mild_crossrecon_samplecovcond/z5/trial1.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_hh/mild_crossrecon_samplecovcond/z5/trial2/models/final_100.pth --cov >> logs/2023/downsampled/bp_hh/mild_crossrecon_samplecovcond/z5/trial2.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_hh/mild_crossrecon_samplecovcond/z5/trial3/models/final_100.pth --cov >> logs/2023/downsampled/bp_hh/mild_crossrecon_samplecovcond/z5/trial3.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_hh/vae_crossrecon_samplecovcond/z5/trial0/models/final_100.pth --cov >> logs/2023/downsampled/bp_hh/vae_crossrecon_samplecovcond/z5/trial0.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_hh/vae_crossrecon_samplecovcond/z5/trial1/models/final_100.pth --cov >> logs/2023/downsampled/bp_hh/vae_crossrecon_samplecovcond/z5/trial1.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_hh/vae_crossrecon_samplecovcond/z5/trial2/models/final_100.pth --cov >> logs/2023/downsampled/bp_hh/vae_crossrecon_samplecovcond/z5/trial2.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_hh/vae_crossrecon_samplecovcond/z5/trial3/models/final_100.pth --cov >> logs/2023/downsampled/bp_hh/vae_crossrecon_samplecovcond/z5/trial3.txt &

