CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_pepper/mild_crossrecon_nocovcondsampling/z5/trial0/models/final_199.pth >> logs/2023/downsampled/bp_pepper/mild_crossrecon_nocovcondsampling/z5/trial0.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_pepper/mild_crossrecon_nocovcondsampling/z5/trial1/models/final_199.pth >> logs/2023/downsampled/bp_pepper/mild_crossrecon_nocovcondsampling/z5/trial1.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_pepper/mild_crossrecon_nocovcondsampling/z5/trial2/models/final_199.pth >> logs/2023/downsampled/bp_pepper/mild_crossrecon_nocovcondsampling/z5/trial2.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_pepper/mild_crossrecon_nocovcondsampling/z5/trial3/models/final_199.pth >> logs/2023/downsampled/bp_pepper/mild_crossrecon_nocovcondsampling/z5/trial3.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_pepper/vae_crossrecon_nocovcondsampling/z5/trial0/models/final_199.pth >> logs/2023/downsampled/bp_pepper/vae_crossrecon_nocovcondsampling/z5/trial0.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_pepper/vae_crossrecon_nocovcondsampling/z5/trial1/models/final_199.pth >> logs/2023/downsampled/bp_pepper/vae_crossrecon_nocovcondsampling/z5/trial1.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_pepper/vae_crossrecon_nocovcondsampling/z5/trial2/models/final_199.pth >> logs/2023/downsampled/bp_pepper/vae_crossrecon_nocovcondsampling/z5/trial2.txt &
CUDA_VISIBLE_DEVICES=3 nohup python3 finetune_robotdecoder.py --ckpt logs/2023/downsampled/bp_pepper/vae_crossrecon_nocovcondsampling/z5/trial3/models/final_199.pth >> logs/2023/downsampled/bp_pepper/vae_crossrecon_nocovcondsampling/z5/trial3.txt &

