CUDA_VISIBLE_DEVICES=1 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_vanilla/z5/trial0 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_vanilla/z5/trial0.txt &
CUDA_VISIBLE_DEVICES=1 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_vanilla/z5/trial1 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_vanilla/z5/trial1.txt &
CUDA_VISIBLE_DEVICES=0 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_vanilla/z5/trial2 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_vanilla/z5/trial2.txt &
CUDA_VISIBLE_DEVICES=0 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_vanilla/z5/trial3 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_vanilla/z5/trial3.txt &

CUDA_VISIBLE_DEVICES=0 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_samplenocovcond/z5/trial0 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_samplenocovcond/z5/trial0.txt &
CUDA_VISIBLE_DEVICES=0 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_samplenocovcond/z5/trial1 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_samplenocovcond/z5/trial1.txt &
CUDA_VISIBLE_DEVICES=0 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_samplenocovcond/z5/trial2 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_samplenocovcond/z5/trial2.txt &
CUDA_VISIBLE_DEVICES=0 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_samplenocovcond/z5/trial3 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_samplenocovcond/z5/trial3.txt &

CUDA_VISIBLE_DEVICES=0 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_samplecovcond/z5/trial0 --cov-cond --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_samplecovcond/z5/trial0.txt &
CUDA_VISIBLE_DEVICES=0 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_samplecovcond/z5/trial1 --cov-cond --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_samplecovcond/z5/trial1.txt &
CUDA_VISIBLE_DEVICES=0 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_samplecovcond/z5/trial2 --cov-cond --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_samplecovcond/z5/trial2.txt &
CUDA_VISIBLE_DEVICES=0 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_samplecovcond/z5/trial3 --cov-cond --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_samplecovcond/z5/trial3.txt &

CUDA_VISIBLE_DEVICES=1 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_covcondsampling/z5/trial0 --cov-cond --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_covcondsampling/z5/trial0.txt &
CUDA_VISIBLE_DEVICES=1 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_covcondsampling/z5/trial1 --cov-cond --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_covcondsampling/z5/trial1.txt &
CUDA_VISIBLE_DEVICES=1 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_covcondsampling/z5/trial2 --cov-cond --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_covcondsampling/z5/trial2.txt &
CUDA_VISIBLE_DEVICES=1 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_covcondsampling/z5/trial3 --cov-cond --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_covcondsampling/z5/trial3.txt &

CUDA_VISIBLE_DEVICES=1 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_nocovcondsampling/z5/trial0 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_nocovcondsampling/z5/trial0.txt &
CUDA_VISIBLE_DEVICES=1 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_nocovcondsampling/z5/trial1 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_nocovcondsampling/z5/trial1.txt &
CUDA_VISIBLE_DEVICES=1 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_nocovcondsampling/z5/trial2 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_nocovcondsampling/z5/trial2.txt &
CUDA_VISIBLE_DEVICES=1 nohup python3 train.py --results logs/2023/bp_pepper_downsampled_robotfuture/vae_nocovcondsampling/z5/trial3 --latent-dim 5 --hsmm-components 5 --model VAE --dataset buetepage_pepper >> logs/2023/bp_pepper_downsampled_robotfuture/vae_nocovcondsampling/z5/trial3.txt &
